apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgA2oNmPnGUoC4uCVceixhparfSEYedDDhy1f1TgIjsPkCAuvpcNCk/+tsg8FbwM70/TY7k2X/E6ZpbC8CzuHlMvRSdUPCvUt73dDtyVjepOprKOvEAIQQ2IoTCELVl5CeW/zt5dDExTBsaTHl7sUVB91TxwClxOYRzD4tzlMIKzi7Wo+QVsbmCqWOZOtQAJQx5ipSRHxWzpHLMCG8lhhxjriVjOj4pntsICveDIFqVzCoLq+dOxDNjFGzcRmjC8zDVQir/jQTmWCE1vNp4Ug71j6GWN+xzw/p/lDu5C+8bleneV6ZYpMNDn/VVlvMQF9SGMxsNvtoc7ZlxwPKHnvjAOY39/eoZtl2Ejl/UQfJy7JBaNdlc9TgiXSMd8JizvyhU0ADkshnJlSc6E+Dr87i2hbw8CphL9QHJnhMgSyJiHjMNP9PMCh8Kxzm2wcFuqmj0RUT1ysLFUogxITGBa8v8ZTVbJWyaUgp33SjGGalP/pKWwYnuYCGS3aX5jCsMJL9i+JFUZ5UpCzGa/tBKUSq1DBI7xJcGNMiE+daNL7CbjE0dSrDMjxpmpqMBXVNFJHkt5bDahYzdoe9slzlvyCOjIiMwsAPb9r3LrTB+9oEk8R2vMv28ocDXs9283WhobAQvsa/6e18f6m6j2f0mn9yY3R66+DmkhLD0YSHDK6MTaDrOdNDGAKoyQEUZxFU+985bdrIxmEZAFglTbRSKOBjrOg778f0GMt6UGBEHGRkFpi6Fm5h163Q==
    ARTIFACTORY_PASSWORD: AgCRXMXbKzG78YwyF4Tm85I7B8lcOFzphJ/C/r8B69q5v4Xu8tYjSRDlzeeTRmDpLQZhvyvNxnhlBIVpBHhyaLNALJSFLRDkB0e3dJOKGO6UR7XC6+8jLENcf/9VCiSNp0Z/ZT3+jK5Oyf+Sn5AoS1d938PEQrdmoGODp46IiKySKjSzCGV3O2camUZxWi6uAgL1r/CVRbeyCEXRbNRpxk8g6OL0TjUWaTMpOhCIgSsn9S5cUcYpHhihy8tsEGzQpijI3A/czAwspW8AZbWc1sh92Bqwoth+Vg7SiNovULmJH3Am1nS2SwWv+nLiE1Eu6yUGpJmIZscUjZ3kcw7s3o9vQh7MJTgNWzHbb0pIKKfTJCsG768/IZEvGfULRS88cA5/9oWjqWnc+PnzG/EXr0fG5D/6fXb8g+BzAyEn+ev8nMwtuljLPFk+CsMkQeGnQ4Q8ertihoe0MjmBOrk6o7Pl0H26DZqUzn+kaKHJKniQ7yO7TrbfmP/ObE0kNylzYHrmUwE6Z8RSoIYg+9dXYCM/hq6cwjPFTBDKINrzpaZVns+195XwMnkCSzBWCva3CiU79qwvI+shr7IvoJjBYhJGUqeDQSWBSx0GQ/SOyc2ee4a/1ohM6fv8+uwt61h3syz9bqp144zcQz2rhCkYkjLbzKKL+Xs0i8IsrEHAcUGvsy/n/6BYCihq7d/wgbiURJknJtBHpgmEsa/10g7iTovhnPsXyQ==
    ARTIFACTORY_URL: AgC8i1PfJhSv+YJ25yOYIRRiLD7yTLt9pr6lrSupFXaXSAmr5hjysnWmLIinRzW60CllmcYPv9+Ji29v7jzgXOpWP3+i2e7mHv+30exTADkD4SwQDnQOCjm6dqAFo1kyFo627gzn4lNQl2FnRMzVvr+O8nQrK6Ztu6krAVA8PzzfrgaHCeiBbGUWXvzRna7rBKgUxm2xcUhLjcjSNbJDdcxHKJ7q+64xkPfeNPPnfyIm+Qf8qjf2RxgyaMDPtqVrQJBkqcRuvi/iAV9jysaiA+K3wRQH8J3YReekgTG1/z8JwBEJuWqKJ9jWGZyBgXeDcXencaMSFkowQtwWwS2F76ymTKpOTPPDLXDR2jPpWilBninWOPfm2HjzBBJzfNHtWWFzwAqPTeurTGdYURYxX4YbeHKxmjifABXU89GbM87JeYr4rxtusJDpLjEzNRf+YsGI+mC/KvmWuRhvqJzBRCXhb4ty6Rg3bqEbOcN2eB4tLlb856INrb2z3pNJNCP+/5IVvMTVrB8+/Y6g9CTvCjyiP+9bUTwLcxxctapL5RKqMPiAzU1hJ2vcGKVfCnLwpqawtbMGlnHfGEYhXF0UOXe78XsvSNljxYkt19D+onFuwzYE3R3jWH4C3gFidHgYVRqGLggvOp3qS8zBmIVYtrWtc5eu2o/AFCL5ot94KYZKcwVP1td8gEgVFRAUJM8VWoeoO2mhxsMNzy8VHXNlAy2jnpNJnC/S95igZjhFMkqqNznQdHfR30JKZw==
    ARTIFACTORY_USER: AgBeHbKGqX/yyfGnjWxAMtFU7TeOteklRfIm+Mwao7l9q4lQvudbqsmsSGoKN+aErr8lMpftHAGazLMWpOISJnYBnUT4z57j3RklvItLBJIn8REKisOgWbuOeKsur3PRd4SdW1ljdQonnabtkYszAJNgfhYxE1lTR102PoWuFE62gt7MEOLQP06IlYkxco1GV6sfWzJXOcnaMQqh6Fnr8btnadOHf0vblTTXOfT+HDA/+YHy2syzQCEK99LMd0ovxFJDdnB4RIUDayXC3lGZvZl+gvppBf28kvmXSxSeqtLO13vAqOPjm2sr5mKBdJ83uoAGaubQNZdkDXdFJz7EtBP0F6aDGV9a66h+EEZy0pxNV0WJuJGfxhPJCKq8ybe2Mp5REOM/Bd6yJmTqt4lMRz81zBJI2NvZRCSJpKX1NF/2Uwfu7m1MYhuV0IfroWuBoamjiCY1U3qFX4uTLtdpY37E8cxanDqFQNOd/fIzik58R3mpkGeZve1L1Y4Bx3xWehq5aioSEX/09e/vLR8FqYmtPD1kKHKyobsXhk1waWD2RKlsp0J82huKYd0E631kgs+bNvOVcT8eTFmBWhSLws/QmwFDz5qbIx4cBSpKWG2r1Od1ZBB1Y8FMBdfC8Zlx2pS5jqcESfoMJvZ9WZ6m7JzwfXR7FEa1V27AOVMPJmyYlBRrf8aYghkiLo1/u+35Ta0+2bf9Rg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2022-01-25T17:08:56Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2022-01-25T17:10:14Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

